accepted = [
    "MIT",
    "Apache-2.0",
    "BSD-3-Clause",
    "BSD-2-Clause",
    "Zlib",
    "Unicode-DFS-2016",
    "Unicode-3.0",
    "BSL-1.0",
    "OFL-1.1",
    "Ubuntu-font-1.0",
    "CC0-1.0",
    "NCSA",
    "ISC"
]


[self_cell.clarify]
license = "Apache-2.0"

[[self_cell.clarify.files]]
path = "LICENSE-APACHE"
license = "Apache-2.0"
checksum = "c71d239df91726fc519c6eb72d318ec65820627232b2f796219e87dcf35d0ab4"